const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1400, height: 900 } });
  await page.goto('http://localhost:3000', { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => localStorage.clear());
  await page.reload({ waitUntil: 'domcontentloaded' });
  await page.waitForTimeout(500);
  await page.click('text=+ New Scenario');
  await page.locator('input[type=number]').first().fill('10000');
  await page.click('text=+ DACH');
  await page.waitForTimeout(300);
  await page.click('text=Awareness');
  await page.click('text=YouTube');
  await page.waitForTimeout(500);
  const el = await page.locator('text=Impressions').first();
  await el.scrollIntoViewIfNeeded();
  await page.waitForTimeout(300);
  await page.screenshot({ path: 'e2e_funnel_scrolled.png' });
  console.log('DONE');
  await browser.close();
})();
