import { importLegacyPlan, isLegacyPlanFile } from '../src/lib/legacyImport';

const raw = {
  scenario_names: ['Scenario 1'],
  custom_templates: {},
  pct_DE_0: 100.0,
  sb_li_Conversion_0: true,
  sb_s_Conversion_0: true,
  mkt_tog_DE_0: false,
  mql_to_sql_DE_LinkedIn_Conversion_0: 30.0,
  cpc_DE_Search_Conversion_0: 1.5,
  mkt_exp_DE_0: true,
  conv_rate_DE_LinkedIn_Conversion_0: 2.0,
  industry: 'Logistics, Supply Chain & Transportation',
  tpl_0: '— pick a template —',
  sb_yt_Conversion_0: false,
  open_rate_DE_LinkedIn_Conversion_0: 45.0,
  sb_s_Awareness_0: false,
  click_to_session_DE_Search_Conversion_0: 70.0,
  sb_yt_Traffic_0: false,
  mql_to_sql_DE_Search_Conversion_0: 35.0,
  breakdown: 'Weekly',
  start_date: { __date__: '2026-05-12' },
  sb_dis_Awareness_0: false,
  sb_li_Awareness_0: false,
  audience_type: 'B2B',
  selected_markets_0: ['DE'],
  split_DE_Conversion_0: 65,
  li_fmt_DE_Conversion_0: 'Sponsored Message / Conversational Ad',
  lead_to_mql_DE_Search_Conversion_0: 25.0,
  campaign_name: 'Lineage_w_Search_&_Linkedin_DE_plan_V2',
  sb_dis_Traffic_0: false,
  end_date: { __date__: '2026-06-29' },
  ctr_DE_LinkedIn_Conversion_0: 0.5,
  rename_0: 'Scenario 1',
  sb_s_Traffic_0: false,
  total_budget_0: 3000,
  sb_dis_Conversion_0: false,
  sb_li_Traffic_0: false,
  conv_rate_DE_Search_Conversion_0: 1.5,
  ctr_DE_Search_Conversion_0: 4.5,
  sb_goal_Traffic_0: false,
  sb_goal_Conversion_0: true,
  tpl_name_0: '',
  sb_yt_Awareness_0: false,
  sb_goal_Awareness_0: false,
  lead_to_mql_DE_LinkedIn_Conversion_0: 20.0,
  cpm_DE_LinkedIn_Conversion_0: 1.5,
};

console.log('isLegacyPlanFile:', isLegacyPlanFile(raw));
const result = importLegacyPlan(raw);
console.log(JSON.stringify(result, null, 2));
